services:
  app:
    build:
      context: ./app
      target: app_prod
      args:
        - APP_USER=${APP_USER:-app}
        - APP_USER_ID=${APP_USER_ID:-1000}
    environment:
      - DATABASE_URL=postgresql://${APP_USER:-app}:${DB_PSWD:-!ChangeMe!}@db:5432/${DB_NAME:-app}?serverVersion=16&charset=utf8
    depends_on:
      - db
    networks:
      - frontend
      - backend
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${DB_NAME:-app}
      - POSTGRES_PASSWORD=${DB_PSWD:-!ChangeMe!}
      - POSTGRES_USER=${APP_USER:-app}
    networks:
      - backend
    volumes:
      - db_data:/var/lib/postgresql/data
  proxy:
    build:
      context: ./app
      target: proxy
      args:
        - APP_USER=${APP_USER:-app}
        - APP_USER_ID=${APP_USER_ID:-1000}
    depends_on:
      - app
    networks:
      - frontend
    ports:
      - ${APP_PORT:-80}:80

volumes:
  db_data:

networks:
  backend:
  frontend:
