services:
  app:
    build:
      target: app_dev
    volumes:
      - ./app:/var/www/html
      ### Use var directory to add necessary configs such as xdebug
      # - ./var/app/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      ### Uncomment below to use your composer cache
      ### See: composer config -gl | grep 'cache-dir'
      # - $HOME/.cache/composer:/home/$APP_USER/.composer/cache
    extra_hosts:
      ### Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
  db:
    ports:
      - 5432:5432
  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        - APP_USER=${APP_USER}
        - APP_USER_ID=${APP_USER_ID}
    environment:
      - DATABASE_URL=postgresql://${APP_USER}:${DB_PSWD}@db:5432/${DB_NAME}?serverVersion=16&charset=utf8
    volumes:
      - .:/workspace
      ### Add various user settings
      # - $HOME/.gitconfig:/home/$APP_USER/.gitconfig
      # - $HOME/.ssh:/home/$APP_USER/.ssh
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - frontend
      - backend
  proxy:
    volumes:
      - ./app/public:/var/www/html/public

volumes:
  db_data:
    ### Use var directory to store db data
    # driver: local
    # driver_opts:
    #   o: bind
    #   type: none
    #   device: ./var/db
